function[t,I_bar,S_bar,R_bar,E_bar,daily_new_inf,yearly_infection]=run_epi_1968_2019_fixed_hh
% Generates annual measles incidence from 1968 - 2019 assuming fixed household
% size according to the household size data and stores the outcome in a mat-file
% The simulation can be run faster using mex file (written in C++) to
% generate random numbers. This is disabled here to prevent issues with
% computer architecture and compilation

% Uses mat file generated by 'run_epi_1968_2019.m' as initial input

%rng('shuffle')
%mex create_brand.cpp

%params fixed
popH = 5e4;
seed = 1e-6;
g = 1/5;
sigma = 1/8;
R0=16;
year_table = 1968:2019;
split = find(year_table == 1968);
tau = (R0-.6404)/3.714;

% alpha = dummy_alpha;
alpha = .1;

% Set up differential equation to solve for H
dt_H=1;    dQ=10;  run_time=365*1;
options=odeset('RelTol', 1e-3);

filename ="alpha/sim_alpha_0.1_140923_214152.mat"

tb=load(filename);

alpha=tb.alpha
%create a struct for storing all values
t =zeros(1,run_time*length(year_table)); S_bar=zeros(1,run_time*length(year_table));      E_bar=zeros(run_time*length(year_table),1);
I_bar=zeros(1,run_time*length(year_table));   R_bar=zeros(run_time*length(year_table),1);
yearly_infection=zeros(length(year_table),1);    daily_new_inf=zeros(run_time*length(year_table),1);
H=[];   P_R_yearly = zeros(length(year_table),1);

t(1:split*run_time)=tb.t(1:split*run_time);
S_bar(1:split*run_time)=tb.S_bar(1:split*run_time);
E_bar(1:split*run_time)=tb.E_bar(1:split*run_time);
I_bar(1:split*run_time)=tb.I_bar(1:split*run_time);
R_bar(1:split*run_time)=tb.R_bar(1:split*run_time);
daily_new_inf(1:split*run_time)=tb.daily_new_inf(1:split*run_time);
yearly_infection(1:split) = tb.yearly_infection(1:split);
P_R_yearly(1:split) = tb.P_R_yearly(1:split);
H=tb.H;

H_init1 = tb.H{split};
P_R1 = P_R_yearly(split);

year = year_table(split);
filename=['MixingData/ClassMixingData',num2str(year)]
tb1=load(filename,'E1','NGrid', 'tickGrid','ClassProb','DemGrid',...
    'TB','kB','TL','kL','kV','TV','TD','kR','Distrib_Children','StopProb','Vacc_rate');
if(isnan(tb1.Vacc_rate));   Vacc_rate=0; else;  Vacc_rate = tb1.Vacc_rate;    end

tb2=load('ContactMixingData','D_All','D_Ext');
d_int=sum(tb1.ClassProb*(tb2.D_All-tb2.D_Ext));
beta = tau*d_int; % tau is Unit time transmission rate based on Hope-Simpson
Inf_Ext=tau*tb2.D_Ext;

[TR,~,~,VectN,Vect,nVect,nTicker,nVectN,E1,E2] = Get_Eq_Demography_seir(popH,tb1.TB,tb1.kB,tb1.TL,tb1.kL,tb1.kV,tb1.TV,tb1.TD,tb1.kR,tb1.Distrib_Children,tb1.StopProb,Vacc_rate,tb1.NGrid,tb1.tickGrid,tb1.E1);
nVectS = nVect(1,:);    nVectE = nVect(2,:);    nVectI = nVect(3,:); nVectR = nVect(4,:);

for i=split+1:length(year_table)
    year = year_table(i);

    filename=['MixingData/ClassMixingData',num2str(year)]
    tb3=load(filename,'Vacc_rate');
    if(isnan(tb3.Vacc_rate));   Vacc_rate=0; else;  Vacc_rate = tb3.Vacc_rate;    end

    H_init = round(H_init1);
    H_init(nVectI==1 & nVectS==2 & nVectE==0 & nVectR==0 & nTicker==4)=H_init(nVectI==1 & nVectS==2 & nVectE==0 & nVectR==0 & nTicker==4)+1;

    [t_i,I_bar_i,S_bar_i,E_bar_i,R_bar_i,H_init1,P_R1,new_inf] = Get_I_seir_stochastic(run_time,H_init,P_R1,options,dt_H,dQ,VectN,Vect,nVect,nVectN,tb1.NGrid,nTicker,tb1.tickGrid,...
        tb1.StopProb,E1,E2,tb1.DemGrid,alpha,beta,Inf_Ext,g,sigma,Vacc_rate,tb1.kB,tb1.kV,tb1.kL,tb1.kR,tb1.TB,tb1.TV,tb1.TL,TR,seed);

    t((i-1)*run_time+1:i*run_time)=t_i+t((i-1)*run_time);
    S_bar((i-1)*run_time+1:i*run_time)=S_bar_i;
    E_bar((i-1)*run_time+1:i*run_time)=E_bar_i;
    I_bar((i-1)*run_time+1:i*run_time)=I_bar_i;
    R_bar((i-1)*run_time+1:i*run_time)=R_bar_i;
    daily_new_inf((i-1)*run_time+1:i*run_time)=new_inf;
    cum_inf = cumsum(new_inf);
    yearly_infection(i) = round((cum_inf(end)/sum(round(nVectN.*H_init1')))*1e5);
    H{i} = H_init1;
end

filename = ['sim_scenario68_alpha_' num2str(alpha) '_' datestr(now,'ddmmyy_HHMMSS') '.mat']
save(filename,'t','I_bar','S_bar','R_bar','E_bar','daily_new_inf','yearly_infection','popH','seed','R0','g','sigma','alpha','H')
end



